### ISSUE TITLE
Java compatibility issue

### ISSUE THREAD

**Issue by Rapster** [xdev-software/chartjs-java-model#14]
Hi,

The project seems to be compiled in java 17, while it was possible to use it in java 7 (from mdewilde). At minimum, I think it should be possible to use it in a java 8 environnement:

> ChartJS.java:[14,42] cannot access software.xdev.chartjs.model.charts.Chart
[ERROR]   bad class file: C:\Users\sebas\.m2\repository\com\xdev-software\chartjs-java-model\1.0.0\chartjs-java-model-1.0.0.jar(software/xdev/chartjs/model/charts/Chart.class)
[ERROR]     class file has wrong version 61.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

Also jackson is compatible java 8, so no need to push the version to 17

**Comment by AB-xdev** [comment]
This repository is - as all our repositories - extended from a template. The template is set to the latest LTS which is currently 17.

In theory it would be possible to set the version to 8 or 11 however
* these versions are by now pretty old and outdated, people should consider updating their applications
  * Java 8 is now nearly 10 years old (and also only partially supported anymore) - people should really consider updating as it runs completely out of support in the next years
  * Java 11 is also 5 years old by now and the migration effort from 11 to 17 is nearly 0 so sticking with that version is also not really required
* going back would require rewriting some code as some features introduced in newer versions don't exist... and then switching back in a few years

I'm willing to reconsider this issue if enough people want a Java 8 compatible version but due to the above reasons for now I don't think that we will implement support for Java 8.

**Comment by Rapster** [comment]
I'm trying my luck here, but I (with the rest of PrimeFaces team) am in discussion to do a rework of our ChartJS component. In a few words, PF has been writing his own java impl of chartJS model: it's not as advanced as yours and not compatible 4.4. I would love to give the possibility for our community to use a more complete and fluent API such as this one. I think this decision will work in favor of xdev-software, since PF community is quite active

We recently migrated to java 11, but as long as chartjs-java-model  requires java 17, we can't expect some of our users to do that kind of upgrade and we have to stick to our current impl... Is there any chance to revisit java compatibility, or maybe have a dedicated branch/release for java 11?

cc @melloware

**Comment by melloware** [comment]
Java 11 is definitely still very popular and it's an LTS release.  Unless you need 17 features it seems odd to make 17 the default required?

**Comment by AB-xdev** [comment]
Okay fine I added support for Java 11 (had to sacrifices some Java 17 code).

However be aware that we can't guarantee support for Java 11 in the long run, so this is for now a "best effort" solution.

**Comment by AB-xdev** [comment]
Released with ``1.0.2``

**Comment by melloware** [comment]
you rock @AB-xdev !!!

**Comment by Rapster** [comment]
Awesome! Thank you @AB-xdev! Sorry you had to downgrade few things on your end
