### ISSUE TITLE
Setting currency format

### ISSUE THREAD

**Issue by SkylerMime** [xdev-software/chartjs-java-model#233]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

I'm working on migrating from the old PrimeFaces p:lineChart to the p:chart element, but I'm not sure how to give setFormat the object it requires for currencies in the axis.

Here's the original JS object:
```JS
currencyFormatOptions = { style: 'currency', currency: 'USD' };
currencyFormat = new Intl.NumberFormat('en-US', currencyFormatOptions);
```

I want to know the Java equivalent for setting format here -- what should myCurrencyFormat be? The given type is just "Object."

```Java
private LineOptions getChartOptions() {
    LineOptions options = new LineOptions();
    options.setScales(new Scales().addScale(ScaleAxis.Y, new CoreScaleOptions().setTicks(new LinearTickOptions().setFormat(myCurrencyFormat))));
    return options;
}
```

**Comment by AB-xdev** [comment]
So the ``format`` field seems to be something that was left over from ChartJS 2.

In ChartJS 3+ you should use ``callback``:
https://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats

Example code:
```java
options
	.getScales()
	.addScale(Scales.ScaleAxis.Y, new LinearScaleOptions()
		.setTicks(new LinearTickOptions()
			.setCallback(new JavaScriptFunction("(label) => `$ ${label}`")))); // JS Code goes here
```

**Comment by AB-xdev** [comment]
I added some example code/tests:
https://github.com/xdev-software/chartjs-java-model/commit/64c503bba7e01f960960ee08a4ac88e88647a797

Note that there is a slight rendering difference between using ``format`` and ``callback``:
When using ``format`` the ``0`` has no ``$``

**Comment by SkylerMime** [comment]
Excellent, thanks for digging this up! The callback solution made more sense for me so I could have $0.00 on the axis:

```Java
options.getScales().addScale(ScaleAxis.Y, new LinearScaleOptions().setTicks(new LinearTickOptions().setCallback(
		new JavaScriptFunction("(label) => Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD'}).format(label)")
)));
```

**Comment by lprender** [comment]
How do you use the resulting json in your client? When I use your example and send it over to my angular client as json it cannot be parsed because of the function. How do I properly parse and use it?

```
fetch(`${environment.apiUrl}/calc/chart/data/pertact/${this.selectedTactId}`)
        .then(response => {
          response.json();
        })
        .then(data => this.chartData = data)
        .catch(error => console.error('Error:', error));
```

But this sadly resolves in the following error:

![image](https://github.com/user-attachments/assets/0894b7e3-cb60-491d-b8f7-89532b182aa9)

**Comment by AB-xdev** [comment]
@lprender 
I'm not quite sure how this is related to the current issue but I will still give it a go.

ChartJS configuration is not valid JSON in the first place, because there is custom stuff like functions inside.

The library is also primarily designed for server generated pages and not really for passing the configuration from the server to the client (it's better to just pass the corresponding data to the client instead and then handle chart creation there).

However if you still want to get the configuration from the backend you can use something like a custom JSON parser or [``eval``](https://stackoverflow.com/a/1086415) to create a valid JS object that can be supplied to ChartJS.
