### ISSUE TITLE
How to access SNAPSHOT version from the CI build?

### ISSUE THREAD

**Issue by aripddev** [xdev-software/chartjs-java-model#294]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/chartjs-java-model/issues) or [closed](https://github.com/xdev-software/chartjs-java-model/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

When running the CI to build a Maven project, I am unable to access SNAPSHOT version of your project. I think it will be done by adding below lines to the `pom.xml`. Is it possible to add it?

### Additional information

```xml
<distributionManagement>
  <snapshotRepository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  </snapshotRepository>
  <repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
  </repository>
</distributionManagement>
```

**Comment by AB-xdev** [comment]
Thank you for the issue, however I can't quite follow.

> When running the CI to build a Maven project, I am unable to access SNAPSHOT version of your project

Yes, because we rarely release Snapshot versions (here is the [GitHub workflow file for that](https://github.com/xdev-software/chartjs-java-model/blob/642a78f2479f0b7f4e71233b74b0022e62ca9075/.github/workflows/test-deploy.yml)), as we usually release anyway after a short period when doing changes.

> I think it will be done by adding below lines to the pom.xml. Is it possible to add it?

Do you mean this repo? 
Because it's already present:
https://github.com/xdev-software/chartjs-java-model/blob/642a78f2479f0b7f4e71233b74b0022e62ca9075/chartjs-java-model/pom.xml#L83-L92
